Tender.App/Controllers/AccountsController.cs
using Aio.Db.MSSqlEF;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Tender.App.Service;
using Tender.Models.Models;

namespace Tender.App.Controllers
{
    public class AccountsController : Controller
    {
        private object _he;
        #region Login_Logout
        [HttpGet]
        public ActionResult Login()
        {
            return View(new VENDOR_LOGIN());
        }
        [HttpPost]
        public ActionResult Login(VENDOR_LOGIN obj)
        {
            if (ModelState.IsValid)
            {
                Tuple<VENDER_SESSION, EQResult> _tpl = AccountsService.UserLogin(obj);
                if (_tpl.Item2.SUCCESS && _tpl.Item2.ROWS == 1)
                {
                    var company= AccountsService.UserCompany(_tpl.Item1.VENDOR_ID).Item1;
                    if (_tpl.Item1.PURCHASER == 1)
                    {
                        Session["ssPurcheserCompany"] = company.FirstOrDefault();
                    }
                    else if(_tpl.Item1.SUPPLIER==1){
                        Session["ssSuplierCompany"] = company.ToList();
                    }

                    Session["ssUser"] = _tpl.Item1;
                    Session["_vendorUserId"] = _tpl.Item1.VENDOR_USER_ID;
                    Session["_vendorEmail"] = _tpl.Item1.VENDOR_EMAIL;
                    Session["_orgName"] = _tpl.Item1.ORGANIZATION_NAME;
                    Session["vendorId"] = _tpl.Item1.VENDOR_ID;
                    Session["_supplierStatus"] = _tpl.Item1.SUPPLIER;
                    Session["_purcherserStatus"] = _tpl.Item1.PURCHASER;

                    return RedirectToAction("Index", "Home");
                }
                //ModelState.AddModelError("", _tpl.Item2.MESSAGES);
                ModelState.AddModelError("", "User Id/Password is wrong");
            }
            return View(obj);
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            Session.Clear();
            return Redirect("Login");
        }
        #endregion


        #region Registration
        [HttpGet]
        public ActionResult Registration()
        {
            DropDownFor_Signup();
            return View(new VENDOR());
        }
        [HttpPost]
        public ActionResult Registration(VENDOR obj, VENDOR_COMPANY companyObj)
        {
            obj.PURCHASER = obj.PURCHASER_X == "on" ? 1 : 0;
            obj.PURCHASER_NOTIFY = obj.PURCHASER_NOTIFY_X == "on" ? 1 : 0;
            obj.SUPPLIER = obj.SUPPLIER_X == "on" ? 1 : 0;
            obj.SUPPLIER_NOTIFY = obj.SUPPLIER_NOTIFY_X == "on" ? 1 : 0;

            //if (companyObj.COMPANY_ID == null) {
            //    ModelState.AddModelError("", "Company is required");
            //}
            if (ModelState.IsValid)
            {
                if (obj.SUPPLIER == 0 && obj.PURCHASER == 0)
                {
                    ModelState.AddModelError("", "Select Supplier");
                }
                else if (obj.SUPPLIER == 1 && obj.PURCHASER == 1)
                {
                    ModelState.AddModelError("", "Select Registration Type Purchaser or Supplier any one");
                }
                else
                {
                    obj.VENDOR_ID = Guid.NewGuid().ToString();
                    companyObj.VENDOR_ID = obj.VENDOR_ID;
                    companyObj.FLAG = obj.SUPPLIER_X == "on" ? "S" : "F";

                    EQResult _tpl = AccountsService.registration(obj, companyObj);
                    if (_tpl.SUCCESS && _tpl.ROWS == 2)
                    {
                        Random rnd = new Random();
                        int confirmationToken = rnd.Next(000000, 999999);

                        MAIL_NOTIFICATION_TOKEN tokenObj = new MAIL_NOTIFICATION_TOKEN();
                        tokenObj.VENDOR_EMAIL = obj.VENDOR_EMAIL;
                        tokenObj.TOKEN = confirmationToken;

                        EQResult _tpl1 = AccountsService.SaveToken(tokenObj, "R");
                        if (_tpl1.SUCCESS)
                        {
                            string mailbody = "Your registration confirmation email is " + obj.VENDOR_EMAIL + " that confirm a verification Code is: <h3>" + confirmationToken + "</h3>";

                            SendEMail(obj.VENDOR_EMAIL, "Registration Confirmation Code for http://rfq.prangroup.com/", mailbody);
                            TempData["msg"] = AlertService.SaveSuccess("Please check your email");
                            ViewBag.VENDOR_EMAIL = obj.VENDOR_EMAIL;
                            TempData["regObj"] = obj;
                            TempData["regOk"] = _tpl;
                            return RedirectToAction("RegistrationSuccessfull", obj);
                        }
                    }
                    else if (_tpl.ROWS == 99)
                    {
                        ModelState.AddModelError("", _tpl.MESSAGES);
                    }

                }
            }
            else
            {
                ModelState.AddModelError("", "Something went wrong, try again");
            }
            DropDownFor_Signup();
            return View(obj);
        }
        //again send notification code method for ajax

        public ActionResult AgainSendToken(string email)
        {
            var VENDOR_EMAIL = email;
            if (!String.IsNullOrEmpty(VENDOR_EMAIL.ToString()))
            {
                Random rnd = new Random();
                int confirmationToken = rnd.Next(000000, 999999);

                MAIL_NOTIFICATION_TOKEN tokenObj = new MAIL_NOTIFICATION_TOKEN();
                tokenObj.VENDOR_EMAIL = VENDOR_EMAIL;
                tokenObj.TOKEN = confirmationToken;

                EQResult _tpl1 = AccountsService.SaveToken(tokenObj, "R");
                if (_tpl1.SUCCESS)
                {
                    string mailbody = "Your registration confirmation email is " + VENDOR_EMAIL + " that confirm a verification Code is: <h3>" + confirmationToken + "</h3>";

                    SendEMail(VENDOR_EMAIL, "Registration Confirmation Code for http://rfq.prangroup.com/", mailbody);
                    TempData["msg"] = AlertService.SaveSuccess("Please check your email");
                    ViewBag.VENDOR_EMAIL = VENDOR_EMAIL;
                    //TempData["regObj"] = obj;
                    //TempData["regOk"] = _tpl;
                    //return RedirectToAction("RegistrationSuccessfull", obj);
                    return Json("Successful", JsonRequestBehavior.AllowGet);
                }
            }
            return Json("Error ! Please again regstration", JsonRequestBehavior.AllowGet);
        }

        public ActionResult RegistrationSuccessfull(VENDOR obj)
        {

            return View(obj);
        }
        [HttpPost]
        public ActionResult RegistrationSuccessfull(VENDOR obj, int token)
        {
            if (String.IsNullOrEmpty(token.ToString()))
            {
                //TempData["msg"] = AlertService.SaveSuccess("Please enter verification code");
                return View(obj);
            }
            else
            {
                MAIL_NOTIFICATION_TOKEN tokenObj = new MAIL_NOTIFICATION_TOKEN();
                tokenObj.VENDOR_EMAIL = obj.VENDOR_EMAIL;
                tokenObj.TOKEN = token;
                Tuple<MAIL_NOTIFICATION_TOKEN, EQResult> _tpl = AccountsService.EmailTokenVerify(tokenObj, "R");
                if (!string.IsNullOrEmpty(_tpl.Item1.VENDOR_EMAIL))
                {
                    TempData["msg"] = AlertService.SaveSuccess("Verification Code Matched Successful");
                    return RedirectToAction("RegistrationConfirmation", obj);
                    //return RedirectToAction("RegistrationConfirmation", "Accounts", new { id = tokenObj.VENDOR_EMAIL });
                }
                else
                {
                    TempData["msg"] = AlertService.SaveWarningOK("Verification code not matched");
                    return View(obj);
                }
            }
        }
        public ActionResult RegistrationConfirmation(VENDOR obj)
        {
            EQResult _tpl = AccountsService.email_confirmation(obj.VENDOR_EMAIL);
            TempData["regOk"] = (_tpl.ROWS) == 1 ? "OK" : "NO";
            return View();
        }

        #endregion

        public ActionResult ForgotPassword()
        {
            VENDOR_LOGIN obj = new VENDOR_LOGIN();
            return View(obj);
        }

        [HttpPost]
        public ActionResult ForgotPassword(VENDOR_LOGIN obj)
        {
            Tuple<VENDOR_LOGIN, EQResult> _tpl = AccountsService.EmailVerification(obj);
            string emailAddress = _tpl.Item1.VENDOR_EMAIL;
            if (!string.IsNullOrEmpty(emailAddress))
            {
                Random rnd = new Random();
                int confirmationToken = rnd.Next(000000, 999999);

                MAIL_NOTIFICATION_TOKEN tokenObj = new MAIL_NOTIFICATION_TOKEN();
                tokenObj.VENDOR_EMAIL = obj.VENDOR_EMAIL;
                tokenObj.TOKEN = confirmationToken;

                EQResult _tpl1 = AccountsService.SaveToken(tokenObj, "F");
                if (_tpl1.SUCCESS)
                {
                    SendEMail(obj.VENDOR_EMAIL, "Reset password code for http://rfq.prangroup.com/", confirmationToken.ToString());
                    TempData["msg"] = AlertService.SaveSuccess("Please check your email");
                    ViewBag.VENDOR_EMAIL = obj.VENDOR_EMAIL;
                    return RedirectToAction("TokenMatch", obj);
                }
                else
                {
                    TempData["msg"] = AlertService.SaveWarningOK(_tpl1.MESSAGES);
                }
            }
            else
            {

Tender.App/Controllers/QuotationController.cs
using Aio.Db.MSSqlEF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Tender.App.Service;
using Tender.Models.Models;
using PagedList;

namespace Tender.App.Controllers
{
    public class QuotationController : Controller
    {
        // GET: Bid, For Bidder
        [UserSessionCheck]
        public ActionResult Index(int? page)
        {
            List<RFQ_TenderView> obj = QuotationService.getAllTenderForSupplier((string)Session["vendorId"]).Item1.Where(c => c.APPROVAL_ID == "0").ToList();
            if (obj.Count == 0)
            {
                TempData["msg"] = AlertService.SaveWarningOK("No RFQ found");
            }
            return View(obj.ToPagedList(page ?? 1, pageSize: 8));
        }

        [HttpGet]
        [UserSessionCheck]
        public ActionResult SubmitQuote(string id)
        {
            DropDownFor_Tender();
            RFQ_BIDDING obj = new RFQ_BIDDING();

            Tuple<RFQ_BIDDING, EQResult> _tpl = QuotationService.getTenderById(id);
            if (_tpl.Item2.SUCCESS && _tpl.Item2.ROWS == 1)
            {
                List<RFQ_TNDR_DOCUMENTS> docList = QuotationService.getTenderDocumentList(id).Item1;
                _tpl.Item1.RFQ_TNDR_DOCUMENTS = docList;
                if (_tpl.Item1.LOWER_RATE == "Lower Rate Only")
                {
                    decimal minimumBid = CommonService.getQuotMinimumBidRate(_tpl.Item1.RFQ_NUMBER, (string)Session["vendorId"]);
                    ViewBag.MINIMUM_BID_RATE = minimumBid;
                }
                return View(_tpl.Item1);
            }
            return View(obj);

            //return View(new RFQ_BIDDING());
        }
        [HttpPost]
        public ActionResult SubmitQuote(RFQ_BIDDING obj)
        {
            obj.SUBMIT_DATE = DateTime.Now;
            obj.VENDOR_ID = (string)Session["vendorId"];

            //submit once check
            if (obj.RE_BID == "Submit Once")
            {
                var _tplSubmitType = QuotationService.submitOnceCheck(obj.RFQ_NUMBER,obj.VENDOR_ID);
                if (_tplSubmitType.Item1.Count() >0)
                {
                    TempData["msg"] = AlertService.SaveWarningOK("Alreay apply quotation for this RFQ");
                    return RedirectToAction("Index");
                }
            }

            //lower rate condition check
            if (obj.LOWER_RATE == "Lower Rate Only")
            {
                decimal minimumBid = CommonService.getQuotMinimumBidRate(obj.RFQ_NUMBER, obj.VENDOR_ID);
                if (obj.PRODUCTS_RATE >= minimumBid && minimumBid != 0)
                {
                    TempData["msg"] = AlertService.SaveWarningOK("Submit Rate must be less then your prvious rate. Please apply again");
                    return RedirectToAction("SubmitQuote", new { id = obj.RFQ_NUMBER });
                }
            }
            if (ModelState.IsValid)
            {
                var _tpl = QuotationService.SaveQuotationData(obj);
                if (_tpl.SUCCESS == true)
                {
                    TempData["msg"] = AlertService.SaveSuccessOK();
                }
            }
            else
            {
                var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();
                ModelState.AddModelError("Error", "Invalid Data");

                DropDownFor_Tender();
                return View(obj);
            }
            DropDownFor_Tender();
            return RedirectToAction("Index");
        }
        [UserSessionCheck]
        public ActionResult WiningsBid()
        {
            List<RFQ_BIDDING> obj = QuotationService.winingsBid((string)Session["vendorId"]).Item1;
            return View(obj);
        }
        [UserSessionCheck]
        public ActionResult TotalApplyBids()
        {
            List<RFQ_BIDDING> obj = QuotationService.totalApplyBids((string)Session["vendorId"]).Item1;
            return View(obj);
        }

        [UserSessionCheck]
        public ActionResult QuotDetails(string quotId)
        {
            DropDownFor_Tender();
            RFQ_BIDDING obj = new RFQ_BIDDING();

            Tuple<RFQ_BIDDING, EQResult> _tpl = QuotationService.getQuotById(quotId);
            if (_tpl.Item2.SUCCESS && _tpl.Item2.ROWS == 1)
            {
                List<RFQ_TNDR_DOCUMENTS> docList = QuotationService.getTenderDocumentList(_tpl.Item1.RFQ_NUMBER).Item1;
                _tpl.Item1.RFQ_TNDR_DOCUMENTS = docList;
                return View(_tpl.Item1);
            }
            return View(obj);

        }

        public void DropDownFor_Tender()
        {
            ViewBag.SHIPMENT_MODE = new SelectList(TenderService.getShipmentMode().Item1.ToList(), "SHIPMENT_MODE_ID", "SHIPMENT_MODE_NAME");
            ViewBag.PORT_ID = new SelectList(TenderService.getPort().Item1.ToList(), "PORT_ID", "PORT_NAME");

        }

    }
}

Tender.App/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tender.App/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tender.App/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


@if ((int)Session["_supplierStatus"] == 1 && (int)Session["_purcherserStatus"] == 0)
{
    <div class="row mt-2">
        <div class="col">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-6">

                        <div class="small-box bg-info">
                            <div class="inner text-center">
                                <h3>@ViewBag.WingingsBids</h3>
                                <p>Total Wining RFQ</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="@Url.Action("WiningsBid","Quotation")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">

                        <div class="small-box bg-success">
                            <div class="inner text-center">
                                <h3>@ViewBag.ApplyBids</h3>
                                <p>Total Apply RFQ</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a href="@Url.Action("TotalApplyBids", "Quotation")" class="small-box-footer"> More info<i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-warning">
                            <div class="inner text-center">
                                <h3>@ViewBag.NewBids</h3>
                                <p>New RFQ</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="@Url.Action("Index","Quotation")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-danger">
                            <div class="inner text-center">
                                <h3>@ViewBag.NotWinBid</h3>
                                <p>Not Win RFQ</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pie-graph"></i>
                            </div>
                            <a href="#" class="small-box-footer"> <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                </div>
                <div class="col text-center text-primary mt-5">
                    <img src="~/App_Asset/dist/img/rfqHomePage.jpg" class="img-fluid" />
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row mt-2">
        <div class="col">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-6">

                        <div class="small-box bg-info">
                            <div class="inner text-center">
                                <h3>@ViewBag.totalRFQ</h3>
                                <p>Total RFQ</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="@Url.Action("ViewAllTender", "Tender")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">

                        <div class="small-box bg-success">
                            <div class="inner text-center">
                                <h3>@ViewBag.totalQuto</h3>
                                <p>Total Quotation</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a href="#" class="small-box-footer" style="min-height:30px;"></a>
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-warning">
                            <div class="inner text-center">
                                <h3>@ViewBag.currentRFQ</h3>
                                <p>Current RFQ</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="#" class="small-box-footer" style="min-height:30px;"></a>
                        </div>
                    </div>

                    <div class="col-lg-3 col-6">
                        <div class="small-box bg-danger">
                            <div class="inner text-center">
                                <h3>@ViewBag.totalSupplier</h3>
                                <p>Supplier Registration</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pie-graph"></i>
                            </div>
                            <a href="@Url.Action("ViewAllSupplier", "Accounts")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="card direct-chat direct-chat-warning">
                        <div class="card-header bg-warning p-2 m-2">
                            <h3 class="card-title">Notification for last 7 days</h3>
                            <div class="card-tools">
                                <span title="3 New Messages" class="badge badge-success">
                                    @ViewBag.newRegistrationCount
                                </span>
                                <span title="3 New Messages" class="badge badge-info">
                                    @ViewBag.newSubmitQuotCount
                                </span>
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-card-widget="remove">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="direct-chat-messages">
                                <div class="direct-chat-msg">
                                    @if (@ViewBag.newRegistrationCount > 0)
                                    {
                                        foreach (var item in ViewBag.newRegistration)
                                        {
                                            <span class="badge badge-success">
                                                <a class="text-dark" href="@Url.Action("supplierProfile", "Accounts", new {id = item.VENDOR_ID })">
                                                    @item.ORGANIZATION_NAME Registration at @item.ADDED_DATE
                                                </a>
                                            </span><br />
                                        }
                                    }

                                    @if (@ViewBag.newSubmitQuotCount > 0)
                                    {
                                        foreach (var item in ViewBag.newSubmitQuot)
                                        {
                                            <span class="badge badge-warning">
                                                <a href="@Url.Action("CompareTender","Tender",new { id = item.RFQ_NUMBER })">
                                                    This @item.QUOTE_NUMBER submitted from @item.VENDOR_ID aganist this @item.RFQ_NUMBER at @item.SUBMIT_DATE
                                                </a>
                                            </span>
                                            <br />
                                        }
                                    }
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-md-7">
                    <div class="card direct-chat direct-chat-warning">
                        <div class="card-header bg-success p-2 m-2">
                            <h3 class="card-title">Monthly RFQ Status (@DateTime.Now.ToString("yyyy"))</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                                <button type="button" class="btn btn-tool" data-card-widget="remove">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="chart">
                                <canvas id="chart_bars" class="chart-canvas"></canvas>
                            </div>
                        </div>

                    </div>
                </div>

                @*<div class="col-md-7">
                        <div class="card direct-chat direct-chat-warning">
                            <div class="card-header bg-success p-2 m-2">
                                <h3 class="card-title">Monthly Submitted Tender Status (Current Year)</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div id="chartContainer" style="height:100%; width: 100%;"></div>
                            </div>

                        </div>
                    </div>*@

            </div>
        </div>
    </div>
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"></script>
    <script>

        $(document).ready(function () {
        var repArray =@Html.Raw(Json.Encode(ViewBag.REP));
        var MonthList = @Html.Raw(Json.Encode(ViewBag.MONTHLIST));
        var ctx = $("#chart_bars");
        var bacChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: MonthList,
                datasets: [{
                    label: "Monthly RFQ Status",
                    data: repArray,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1

                }]
            },
            options: {
                maintainAspectRation: false,
                scales: {
                    xAxes: [{ tricks: { beginAtZero: true}}]
                },
                legend: { display: false }
                },
            })




        })


    </script>

}