Tender.App/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tender.App.Service;
using Tender.Models.Models;

namespace Tender.App.Controllers
{
    public class SetupController : Controller
    {
        #region Category
        // GET: Setup
        public ActionResult Categories()
        {
            return View();
        }

        public ActionResult CreateCategory()
        {
            return View();
        }
        public ActionResult CreateCategory(string obj)
        {

            return View();
        }
        #endregion

        #region tenderProduct       
        [HttpGet]
        [UserSessionCheck]
        public ActionResult CreateTenderProduct()
        {
            VENDOR_COMPANY snPurcheserComObj = (VENDOR_COMPANY)Session["ssPurcheserCompany"];
            ViewBag.GROUP_ID = new SelectList(SetupService.getpProductGroup(snPurcheserComObj.COMPANY_ID).Item1.ToList(), "ID", "NAME");
            TNDR_PRODUCTS obj = new TNDR_PRODUCTS();
            return View(obj);
        }
        [HttpPost]
        [UserSessionCheck]
        public ActionResult CreateTenderProduct(TNDR_PRODUCTS obj)
        {
            VENDOR_COMPANY snPurcheserComObj = (VENDOR_COMPANY)Session["ssPurcheserCompany"];
            ViewBag.GROUP_ID = new SelectList(SetupService.getpProductGroup(snPurcheserComObj.COMPANY_ID).Item1.ToList(), "ID", "NAME");
            if (ModelState.IsValid)
            {
                if (SetupService.checkItem(obj.PRODUCTS_NAME).Item1.PRODUCTS_NAME != null)
                {
                    ModelState.AddModelError("", "This Product Name Already Exist");
                    return View(obj);
                }
                if (obj.ProductPicture != null)
                {
                    if (obj.ProductPicture.ContentLength <= 10240*500)
                    {
                        string pic = System.IO.Path.GetFileName(obj.ProductPicture.FileName);
                        var extension = Path.GetExtension(obj.ProductPicture.FileName);
                        string path = System.IO.Path.Combine(
                                               Server.MapPath("~/App_Asset/dist/img/productImage"), pic);
                        System.Drawing.Image UploadedImage = System.Drawing.Image.FromStream(obj.ProductPicture.InputStream);

                        if (UploadedImage.PhysicalDimension.Width == 800 && UploadedImage.PhysicalDimension.Height == 800)
                        {
                            if (extension.ToLower() == ".jpg" || extension.ToLower() == ".png" || extension.ToLower() == "jpeg")
                            {
                                obj.ProductPicture.SaveAs(path);
                                obj.IMAGE_PATH = "App_Asset/dist/img/productImage/" + pic;
                                var _tpl = SetupService.saveItem(obj);
                                using (MemoryStream ms = new MemoryStream())
                                {
                                    obj.ProductPicture.InputStream.CopyTo(ms);
                                    byte[] array = ms.GetBuffer();
                                }
                                if (_tpl.SUCCESS == true)
                                {
                                    TempData["msg"] = AlertService.SaveSuccess();
                                }
                            }
                            else
                            {
                                TempData["msg"] = AlertService.SaveWarningOK("Image format must be jpg, jpeg,png");
                                return View(obj);
                            }
                        }
                        else
                        {
                            TempData["msg"] = AlertService.SaveWarningOK("Image Size must be 800 X 800");
                            return View(obj);
                        }


                    }
                    else
                    {
                        TempData["msg"] = AlertService.SaveWarningOK("Image Size must be less then 500 kb");
                        return View(obj);
                    }
                }
                else
                {
                    var _tpl = SetupService.saveItem(obj);
                    if (_tpl.SUCCESS == true)
                    {
                        TempData["msg"] = AlertService.SaveSuccess();
                    }
                }
            }
            else
            {
                var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();
                ModelState.AddModelError("Err", "Invalid Data");
            }
            return View(obj);
        }

        [UserSessionCheck]
        public ActionResult GetAll()
        {
            VENDOR_COMPANY snPurcheserComObj = (VENDOR_COMPANY)Session["ssPurcheserCompany"];
            List<TNDR_PRODUCTS> obj = SetupService.getAllproduct(snPurcheserComObj.COMPANY_ID).Item1;
            if (obj.Count() > 0)
            {
                return Json(new { data = obj }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { data = new List<TNDR_PRODUCTS>() }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Tender.App/Views/Setup/CreateTenderProduct.cshtml
@model Tender.Models.Models.TNDR_PRODUCTS

@{
    ViewBag.Title = "Create Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12 mt-3">

    <div class="card card-primary">
        <div class="card-header">
            <h5 class="card-title">Create Item</h5>
        </div>


        @using (Html.BeginForm("CreateTenderProduct", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            @Html.AntiForgeryToken()
    <div class="card-body">
        <div class="form-group">
            <label for="exampleInputEmail1">Product Name</label>
            @Html.EditorFor(model => model.PRODUCTS_NAME, new { htmlAttributes = new { @class = "form-control form-control-sm", placeholder = "Product Name" } })
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Unit</label>
            @Html.EditorFor(model => model.UNIT, new { htmlAttributes = new { @class = "form-control form-control-sm", placeholder = "Unit" } })
        </div>
            <div class="form-group">
                <label class="control-label">Select Catagory</label>
                @Html.DropDownList("GROUP_ID", null, "-Select-", new { @class = "form-control form-control-sm select2", placeholder = "Catagory",style="width:100%;" })
                @Html.ValidationMessageFor(m => m.GROUP_ID, "", new { @class = "text-danger" })
            </div>
        <div class="form-group">
            @Html.Label("Upload Product Picture", new { @class = "control-label" })
            <input type="file" name="ProductPicture" accept=".png, .jpg, .jpeg" />
            <br />

            <span class="text-success">png,jpg,jpeg format only</span>
            <span class="text-primary">Maximun Size 100KB</span><br />
            <span class="text-danger">Must be Height 800px Width 800px</span>
        </div>
    </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" id="save" style="display:none;">Save</button>
                <button class="btn btn-primary" id="submit">Submit</button>
            </div>
        }
    </div>

</div>

<div class="col-md-12" id="ItemList">
    <div class="card card-primary card-outline">
        <div class="card-header">
            Item List
        </div>
        <div class="card-body table-responsive">
            <table id="myTable1" class="table table-hover" style="width: 100%;">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Code</th>
                        <th>Catagory</th>
                        <th>Name</th>
                        <th>Unit</th>

                    </tr>
                </thead>
            </table>
        </div>
    </div>


</div>


@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    var myTable;
    $(document).ready(function () {
        //datatable load
        loadTable();

            $("#submit").click(function () {
                $("#save").click();
            });

            function preventBack() { window.history.forward(); }
            setTimeout("preventBack()", 0);
            window.onunload = function () { null };
        })

         function loadTable() {
             let url = "@Url.Action("GetAll")";
             var baseUrl = window.location.origin;
            myTable = $('#myTable1').DataTable({
                "ajax": "GetAll",
                "type": "GET",
                "datatype": "json",
                "bDestroy": false,                
                "paging": true,
                "info": false,
                "responsive": true,
                "ordering": true,
                "columns": [
                    {
                        "mData": "IMAGE_PATH",
                        render: function (mData) {
                            return '<a href="' + baseUrl + '/' + mData +'"> <img src="' + baseUrl+'/'+mData +'" alt="No Image"height="50" width="50"/> </a>'
                        }
                    },
                    { "mData": "PRODUCTS_ID" },
                    { "mData": "GROUP_ID" },
                    { "mData": "PRODUCTS_NAME" },
                    { "mData": "UNIT" }
                ],
                "language": { "emptyTable": "no data found" }, "width": "100%"
            });
        };
    </script>

}